In [67]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os

In [68]:
smartphones_df = pd.read_csv('../../preprocessing/smartphones_preprocessed.csv')

In [69]:
smartphones_df.head()

,brand_name,model,price,avg_rating,5G_or_not,processor_brand,num_cores,processor_speed,battery_capacity,fast_charging_available,...,internal_memory,screen_size,refresh_rate,num_rear_cameras,os,primary_camera_rear,primary_camera_front,extended_memory_available,resolution_height,resolution_width
0,apple,Apple iPhone 11,38999,7.3,0,bionic,6.0,2.65,3110.000000,0,...,64,6.1,60,2,ios,12.0,12.0,0,1792,828
1,apple,Apple iPhone 11 (128GB),46999,7.5,0,bionic,6.0,2.65,3110.000000,0,...,128,6.1,60,2,ios,12.0,12.0,0,1792,828
2,apple,Apple iPhone 11 Pro Max,109900,7.7,0,bionic,6.0,2.65,3500.000000,1,...,64,6.5,60,3,ios,12.0,12.0,0,2688,1242
3,apple,Apple iPhone 12,51999,7.4,1,bionic,6.0,3.10,4817.748194,0,...,64,6.1,60,2,ios,12.0,12.0,0,2532,1170
4,apple,Apple iPhone 12 (128GB),55999,7.5,1,bionic,6.0,3.10,4817.748194,0,...,128,6.1,60,2,ios,12.0,12.0,0,2532,1170

In [70]:
smartphones_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 980 entries, 0 to 979
Data columns (total 22 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   brand_name                 980 non-null    object
 1   model                      980 non-null    object
 2   price                      980 non-null    int64
 3   avg_rating                 980 non-null    float64
 4   5G_or_not                  980 non-null    int64
 5   processor_brand            980 non-null    object
 6   num_cores                  980 non-null    float64
 7   processor_speed            980 non-null    float64
 8   battery_capacity           980 non-null    float64
 9   fast_charging_available    980 non-null    int64
 10  fast_charging              980 non-null    float64
 11  ram_capacity               980 non-null    int64
 12  internal_memory            980 non-null    int64
 13  screen_size                980 non-null    float64
 14  refresh_rate               980 non-null    int64
 15  num_rear_cameras           980 non-null    int64
 16  os                         980 non-null    object
 17  primary_camera_rear        980 non-null    float64
 18  primary_camera_front       980 non-null    float64
 19  extended_memory_available  980 non-null    int64
 20  resolution_height          980 non-null    int64
 21  resolution_width           980 non-null    int64
dtypes: float64(8), int64(10), object(4)
memory usage: 168.6+ KB

In [71]:
smartphones_df = smartphones_df.drop(columns=["brand_name", "model"])

In [73]:
# Izračunajte minimum i maksimum cene
min_price = smartphones_df['price'].min()
max_price = smartphones_df['price'].max()

# Postavite prag cene na 70% između minimuma i maksimuma
price_threshold = min_price + 0.7 * (max_price - min_price)

# Kreirajte novu kolonu "price_binary" sa vrednostima 1 za cene veće od praga, inače 0
smartphones_df['price_binary'] = smartphones_df['price'].apply(lambda x: 1 if x > price_threshold else 0)

In [76]:
smartphones_df = smartphones_df.drop(columns=["price"])

In [77]:
# Izračunajte minimum i maksimum za kolonu "avg_rating"
min_avg_rating = smartphones_df['avg_rating'].min()
max_avg_rating = smartphones_df['avg_rating'].max()

# Postavite prag za "avg_rating" na 50% između minimuma i maksimuma
avg_rating_threshold = min_avg_rating + 0.5 * (max_avg_rating - min_avg_rating)

# Kreirajte novu kolonu "avg_rating_binary" sa vrednostima 1 za ocene veće od praga, inače 0
smartphones_df['avg_rating_binary'] = smartphones_df['avg_rating'].apply(lambda x: 1 if x > avg_rating_threshold else 0)

# Sada DataFrame smartphones_df sadrži novu kolonu "avg_rating_binary" sa binarnim atributom na osnovu 50% između min i max ocena

# Izbacite kolonu "avg_rating"
smartphones_df = smartphones_df.drop(columns=["avg_rating"])

In [78]:
smartphones_df = pd.get_dummies(smartphones_df, columns=["os"], prefix="os")

In [79]:
# Brojanje jedinstvenih vrednosti u koloni "processor_brand"
unique_processor_brands = smartphones_df['processor_brand'].nunique()

# Ispisivanje broja jedinstvenih vrednosti
print("Broj jedinstvenih vrednosti u koloni 'processor_brand':", unique_processor_brands)

Broj jedinstvenih vrednosti u koloni 'processor_brand': 13

In [80]:
smartphones_df['processor_brand'] = pd.factorize(smartphones_df['processor_brand'])[0]

In [82]:
smartphones_df.head()

,5G_or_not,processor_brand,num_cores,processor_speed,battery_capacity,fast_charging_available,fast_charging,ram_capacity,internal_memory,screen_size,...,primary_camera_rear,primary_camera_front,extended_memory_available,resolution_height,resolution_width,price_binary,avg_rating_binary,os_android,os_ios,os_other
0,0,0,6.0,2.65,3110.000000,0,1.0,4,64,6.1,...,12.0,12.0,0,1792,828,0,0,0,1,0
1,0,0,6.0,2.65,3110.000000,0,1.0,4,128,6.1,...,12.0,12.0,0,1792,828,0,1,0,1,0
2,0,0,6.0,2.65,3500.000000,1,18.0,4,64,6.5,...,12.0,12.0,0,2688,1242,0,1,0,1,0
3,1,0,6.0,3.10,4817.748194,0,1.0,4,64,6.1,...,12.0,12.0,0,2532,1170,0,0,0,1,0
4,1,0,6.0,3.10,4817.748194,0,1.0,4,128,6.1,...,12.0,12.0,0,2532,1170,0,1,0,1,0

In [85]:
smartphones_df.isna().any().any()

False

In [86]:
smartphones_df.to_csv('smartphones.csv', index=False)